services:
  postgres:
    image: postgres:17
    container_name: postgres_petshop
    environment:
      POSTGRES_DB: petshop_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 13223108
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  petshop-api:
    build: .
    container_name: petshop-api
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    command: ["java", "-jar", "/app/app.jar"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/petshop_api
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 13223108

volumes:
  postgres_data:



