
services:
  postgres:
    image: postgres:17
    container_name: postgres_petshop
    environment:
      POSTGRES_DB: petshop_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 13223108
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  petshop-api:
    build: .
    container_name: petshop-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    entrypoint: ["/wait-for-it.sh", "postgres:5432", "--"]
    command: ["java", "-jar", "/app/app.jar"]
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/petshop_api
      DB_USER: postgres
      DB_PASSWORD: 13223108

volumes:
  postgres_data:

