

version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_petshop
    environment:
      POSTGRES_DB: petshop_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  petshop-api:
    build: .
    container_name: petshop-api
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # Ativando o perfil
      APP_PROFILE: local

      # Configuração do banco (note o host = "postgres", nome do container)
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/petshop_api
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin

      # Configuração do Hibernate
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    command: ["java", "-jar", "app.jar"]

volumes:
  postgres_data:





