

services:
  postgres:
    image: postgres:17
    container_name: postgres_petshop
    environment:
      POSTGRES_DB: petshop_api
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  petshop-api:
    build: .
    container_name: petshop-api
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    command: ["java", "-jar", "/app/app.jar"]
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  postgres_data:




